/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CharacterIndexRouteImport } from './routes/character/index'

const CharacterIndexRoute = CharacterIndexRouteImport.update({
  id: '/character/',
  path: '/character/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/character': typeof CharacterIndexRoute
}
export interface FileRoutesByTo {
  '/character': typeof CharacterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/character/': typeof CharacterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/character'
  fileRoutesByTo: FileRoutesByTo
  to: '/character'
  id: '__root__' | '/character/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CharacterIndexRoute: typeof CharacterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/character/': {
      id: '/character/'
      path: '/character'
      fullPath: '/character'
      preLoaderRoute: typeof CharacterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  CharacterIndexRoute: CharacterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
